name: Docker build and push
on:   
  push:
    branches:
      - master
  schedule:
    - cron: "0 2 * * 0"

env:
  IMAGE_NAME: java

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        java: [
          '1.8.0',
          '11',
          '16'
        ]

    steps:
      - uses: actions/checkout@v2

      - uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile
          config: hadolint-ci.yaml

      - name: Render docker-compose.yml
        run: JAVA_VERSION=${{ matrix.java }} envsubst <  docker-compose.yml.tmpl >  docker-compose.yml

      - name: Build image
        run: docker-compose -f docker-compose.yml build java

      - name: Log into registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login https://index.docker.io/v1/ -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push image
        run: docker-compose -f docker-compose.yml push java

      - name: Tag build-versioned image
        run: docker tag acornsaustralia/java:${{ matrix.java }} acornsaustralia/java:${{ matrix.java }}-${{ github.run_number }}

      - name: Push versioned image
        run: docker push acornsaustralia/java:${{ matrix.java }}-${{ github.run_number }}
